name: Nest.js CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format:check

